# Generated by Django 4.2 on 2023-06-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default=None, max_length=400, null=True, upload_to='cards/')),
                ('title', models.CharField(max_length=100)),
                ('descript', models.CharField(max_length=1000)),
                ('update', models.CharField(max_length=50)),
            ],
        ),
    ]
