# Generated by Django 4.2 on 2023-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_moviecards_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecards',
            name='m_link',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
