# Generated by Django 4.2 on 2023-06-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_moviecards_m_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecards',
            name='m_link',
            field=models.CharField(max_length=200),
        ),
    ]
