# Generated by Django 4.2 on 2023-06-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_moviecards_m_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecards',
            old_name='m_link',
            new_name='link',
        ),
    ]
