# Generated by Django 4.2 on 2023-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_moviecards_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecards',
            name='link',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
